apiVersion: v1
kind: Service
metadata:
  name: rag-minio
  namespace: rag-workers
spec:
  type: ClusterIP
  selector:
    app: rag-minio
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: minio
      protocol: TCP
      port: 9001
      targetPort: 9001