apiVersion: v1
kind: Service
metadata:
  name: rag-frontend-service
  namespace: rag-frontend

spec:
  type: ClusterIP
  selector:
    app: rag-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
