apiVersion: v1
kind: Service
metadata:
  name: rag-worker
  namespace: rag-workers
spec:
  type: ClusterIP
  selector:
    app: rag-worker
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
