# Use kubectl apply -f api-url-secret.yaml -n <NAMESPACE> fore each namespace to make sure that the pods can read the secrets
#NEVER COMMIT THIS FILE TO A GIT REPO!!!
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-url  
type: Opaque
stringData:
  WEAVIATE_URL: PUT HERE YOU WEAVIATE_URL
---

apiVersion: v1
kind: Secret
metadata:
  name: s3-endpoint-url 
type: Opaque
stringData:
  S3_ENDPOINT_URL: PUT HERE YOUR S3_ENDPOINT_URL
---

apiVersion: v1
kind: Secret
metadata:
  name: worker-url 
type: Opaque
stringData:
  WORKER_URL: PUT HERE YOU WORKER_URL
---

apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key-id 
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: PUT HERE YOUR AWS_ACCESS_KEY_ID
---

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key  
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: PUT HERE YOU AWS_SECRET_ACCESS_KEY
---

apiVersion: v1
kind: Secret
metadata:
  name: cohere-api-key 
type: Opaque
stringData:
  COHERE_API_KEY: PUT HERE YOUR API KEY 
---

apiVersion: v1
kind: Secret
metadata:
  name: api-url 
type: Opaque
stringData:
  API_URL: PUT HERE YOU API URL
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-root-user 
type: Opaque
stringData:
  MINIO_ROOT_USER: PUT HERE YOUR MINIO USER
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-root-password 
type: Opaque
stringData:
  MINIO_ROOT_PASSWORD: PUT HERE YOU MINIO PASSWORD
---



  